import {
  Curvature,
  DEFAULT_PRIOR_SIGMA,
  PoolFit,
  PoolFitOptions,
  bootstrapStrengths,
  fitStrengths,
} from './bradleyTerry';
import {DEFAULT_BOOTSTRAP_REPLICATES, Identity, Observation} from './types';

/**
 * The multiplayer rating fit (Milestone 2, bullet 3, Unit B;
 * agent/docs/Milestone2_Bullet3_Prompts.md §3.3, §3.5, hazard H2/H4).
 *
 * **Plackett-Luce is Bradley-Terry's multiplayer generalization**, and it is the *same latent
 * strength*: a game's finishing order is generated by repeatedly drawing, from the seats still
 * unplaced, in proportion to `exp(theta)`. At two players it reduces exactly to Bradley-Terry, which
 * is why one parameter vector serves both and why `bradleyTerry.ts` owns everything downstream of
 * the fit - the Elo scale, the anchor, the separation logic, the bootstrap.
 *
 * Three decisions that are easy to get wrong and are settled here:
 *
 * **1. Placements are fitted per player count, never pooled** (§3.5). An agent strong at 2p can be
 * weak at 3p - different tempo, a different milestone race, kingmaking - so a pooled latent strength
 * averages two quantities the project cares about separately. 2p is the primary evaluation setting
 * and 3-4p is a distinct competence target (`agent/CLAUDE.md` §1), and the ladder therefore carries
 * `rating[players][identity]`. A pooled figure may be *reported* as a convenience, flagged as
 * assuming strength transfers; it is never the thing a criterion is adjudicated on.
 *
 * **2. One identity may hold several seats, and that is the interesting case** (hazard H2). This
 * bullet's 3p corpus is `greedy-1ply,greedy-1ply,random-legal` precisely because it is the only real
 * data that exercises it. The likelihood handles it without any special case - both seats contribute
 * their own terms and both index the same `theta` - but two things around it do need care, and both
 * are wrong-by-default: the AC-5 null is `seatsHeld / players` rather than `1 / players`
 * (`observations.ts` owns that), and a *whole-lineup* self-match contributes a likelihood that does
 * not depend on `theta` at all and is excluded and counted (§3.6).
 *
 * **3. Ties.** See {@link tieConvention}.
 */

// ---------------------------------------------------------------------------------------------
// The tie convention (hazard H4)
// ---------------------------------------------------------------------------------------------

/**
 * **A tied group contributes the average of the log-likelihoods over its internal orderings.**
 *
 * Recorded in code because §3.3 asks for "an explicitly documented convention" and because ties are
 * *unobserved, not absent* (hazard H4): across the 1,700 games bullet 1 committed there were zero
 * shared wins, and this bullet's own 3p corpus produced the project's first - two `greedy-1ply@1`
 * seats on 72 VP and 51 megacredits. One. So whatever is chosen here is nearly free and is
 * **untested by data**, and the write-up must say so rather than implying the convention has been
 * exercised.
 *
 * The alternative considered and rejected was the exact marginal likelihood of the observed partial
 * order, `log( mean over orderings of P )`. It is the "more correct" quantity, and with at most four
 * seats it is cheap to enumerate. It was rejected because it is **not concave in theta**: a mixture
 * of Plackett-Luce likelihoods is a sum of concave-in-log terms, not a concave one, so the fit would
 * lose the single-maximum guarantee that `maximizeLogPosterior`'s whole argument rests on - and it
 * would lose it in exchange for a difference that, at one tied pair in ~4,300 games, is far below
 * the width of any interval this pipeline reports. `mean of log P` is concave (an average of concave
 * functions), it is exactly the expected log-likelihood under uniform tie-breaking, and it agrees
 * with the exact form to first order.
 *
 * The other alternative - breaking ties by seat index - was rejected outright: it is not symmetric
 * in the identities, so at 3p it would hand the tied seat with the lower index a systematic
 * advantage in the fit, and the pairing design cannot average that away when one identity holds two
 * seats.
 */
export const tieConvention =
  'a tied placement group contributes the average of the log-likelihoods over its internal orderings';

// ---------------------------------------------------------------------------------------------
// The ranking patterns
// ---------------------------------------------------------------------------------------------

/**
 * One game's finishing order as identity indices, grouped by placement.
 *
 * `groups[0]` is the set of identity indices that finished first, `groups[1]` second, and so on. A
 * group with more than one member is a tie. Two seats held by the *same* identity in the same group
 * appear twice, which is correct: they are two draws from the same strength.
 */
export type RankingPattern = {groups: ReadonlyArray<ReadonlyArray<number>>};

/** A pattern with the number of games in one cluster that produced it - the bootstrap's atom. */
export type PatternTally = {pattern: RankingPattern; count: number};

export type PlacementSet = {
  identities: ReadonlyArray<Identity>;
  players: 3 | 4;
  /** One entry per pairing group (§3.1). */
  clusters: ReadonlyArray<ReadonlyArray<PatternTally>>;
  games: number;
  /** Games every seat of which held one identity: no information about relative strength (§3.6). */
  selfMatchGames: number;
  gamesPerIdentity: ReadonlyArray<number>;
  /** Games containing at least one tied placement group. Expected to be tiny; see {@link tieConvention}. */
  tiedGames: number;
};

/**
 * Placement patterns from 3p or 4p observation rows, keyed by identity (§3.6, hazard H2).
 *
 * **Patterns are tallied per cluster, not stored per game**, for the same reason `bradleyTerry.ts`
 * tallies pair counts: a 2,000-replicate bootstrap refits 2,000 times, and a 3p lineup admits at
 * most a handful of distinct patterns, so a cluster of six games collapses to at most six entries
 * and a refit costs `iterations x patterns x players²` regardless of the corpus size.
 */
export function buildPlacementSet(rows: ReadonlyArray<Observation>): PlacementSet {
  const players = rows[0]?.players;
  if (players !== 3 && players !== 4) {
    throw new Error(
      `buildPlacementSet is 3p/4p only, and got ${players === undefined ? 'no rows' : `${players}p rows`}. ` +
      'Fit 2p head-to-heads with bradleyTerry.ts (§3.3), and never pool player counts (§3.5).');
  }
  const wrongCount = rows.find((row) => row.players !== players);
  if (wrongCount !== undefined) {
    throw new Error(
      `buildPlacementSet was given both ${players}p and ${wrongCount.players}p rows. A rating scale is ` +
      'per player count (§3.5): an agent strong at 2p can be weak at 3p, and a pooled latent strength ' +
      'averages two quantities the project cares about separately.');
  }

  const identities = [...new Set(rows.map((row) => row.identity))].sort();
  const indexOf = new Map(identities.map((identity, index) => [identity, index]));

  const byGame = new Map<string, Array<Observation>>();
  for (const row of rows) {
    const key = `${row.runId}#${row.groupIndex}#${row.permutationIndex}`;
    const game = byGame.get(key) ?? [];
    game.push(row);
    byGame.set(key, game);
  }

  const byCluster = new Map<string, Map<string, PatternTally>>();
  const gamesPerIdentity = new Array<number>(identities.length).fill(0);
  let games = 0;
  let selfMatchGames = 0;
  let tiedGames = 0;

  for (const key of [...byGame.keys()].sort()) {
    const seats = (byGame.get(key) as ReadonlyArray<Observation>).slice().sort((a, b) => a.seat - b.seat);
    if (seats.length !== players) {
      throw new Error(`${players}p game ${key} has ${seats.length} seat rows; the observation set is malformed`);
    }
    if (new Set(seats.map((seat) => seat.identity)).size === 1) {
      selfMatchGames++;
      continue;
    }
    games++;
    for (const identity of new Set(seats.map((seat) => seat.identity))) {
      gamesPerIdentity[indexOf.get(identity) as number]++;
    }

    const byPlacement = new Map<number, Array<number>>();
    for (const seat of seats) {
      const group = byPlacement.get(seat.placement) ?? [];
      group.push(indexOf.get(seat.identity) as number);
      byPlacement.set(seat.placement, group);
    }
    const pattern: RankingPattern = {
      groups: [...byPlacement.keys()].sort((a, b) => a - b)
        .map((placement) => (byPlacement.get(placement) as Array<number>).sort((a, b) => a - b)),
    };
    if (pattern.groups.some((group) => group.length > 1)) {
      tiedGames++;
    }

    const cluster = byCluster.get(seats[0].clusterId) ?? new Map<string, PatternTally>();
    const patternKey = pattern.groups.map((group) => group.join(',')).join('|');
    const tally = cluster.get(patternKey) ?? {pattern, count: 0};
    tally.count++;
    cluster.set(patternKey, tally);
    byCluster.set(seats[0].clusterId, cluster);
  }

  return {
    identities,
    players,
    clusters: [...byCluster.keys()].sort().map((clusterId) => {
      const cluster = byCluster.get(clusterId) as Map<string, PatternTally>;
      return [...cluster.keys()].sort().map((patternKey) => cluster.get(patternKey) as PatternTally);
    }),
    games,
    selfMatchGames,
    gamesPerIdentity,
    tiedGames,
  };
}

// ---------------------------------------------------------------------------------------------
// The likelihood
// ---------------------------------------------------------------------------------------------

/**
 * The Plackett-Luce log-likelihood over ranking patterns, with its gradient and observed information.
 *
 * For one strict ordering `o` of the seats,
 *
 * ```
 * l(o) = sum over ranks r of [ theta_o(r) - log sum_{s >= r} exp(theta_o(s)) ]
 * ```
 *
 * which is a chain of softmax log-likelihoods over shrinking choice sets. The gradient of each link
 * is `indicator - p`, and its information is `diag(p) - p pᵀ` over the remaining set - the standard
 * multinomial-logit form, positive semi-definite, so the whole log-likelihood is concave and
 * {@link maximizeLogPosterior}'s single-maximum argument carries over from Bradley-Terry unchanged.
 *
 * Tied groups are handled by averaging over their internal orderings; see {@link tieConvention} for
 * why that convention and not the exact marginal.
 */
export function plackettLuceCurvature(
  theta: ReadonlyArray<number>,
  clusters: ReadonlyArray<ReadonlyArray<PatternTally>>,
): Curvature {
  const k = theta.length;
  const gradient = new Array<number>(k).fill(0);
  const information = Array.from({length: k}, () => new Array<number>(k).fill(0));
  let value = 0;

  for (const cluster of clusters) {
    for (const tally of cluster) {
      const orderings = expandTies(tally.pattern);
      const weight = tally.count / orderings.length;
      for (const ordering of orderings) {
        value += weight * accumulateOrdering(theta, ordering, weight, gradient, information);
      }
    }
  }

  return {value, gradient, information};
}

/**
 * One ordering's log-likelihood, adding `weight x` its gradient and information to the accumulators.
 *
 * The `weight` is applied to the derivatives here and to the value by the caller, so that the tie
 * average and the pattern count are the same multiplication applied once in each place.
 */
function accumulateOrdering(
  theta: ReadonlyArray<number>,
  ordering: ReadonlyArray<number>,
  weight: number,
  gradient: Array<number>,
  information: Array<Array<number>>,
): number {
  const n = ordering.length;
  const probabilities = new Array<number>(n).fill(0);
  let value = 0;

  // The last seat's choice set has one member, so its log-likelihood is 0 and its information empty.
  // Indexed rather than sliced: this loop is the inner loop of every bootstrap refit, and a slice
  // per rank per pattern per Newton evaluation is measurable at 2,000 replicates.
  for (let rank = 0; rank < n - 1; rank++) {
    let shift = theta[ordering[rank]];
    for (let s = rank + 1; s < n; s++) {
      shift = Math.max(shift, theta[ordering[s]]);
    }
    let total = 0;
    for (let s = rank; s < n; s++) {
      probabilities[s] = Math.exp(theta[ordering[s]] - shift);
      total += probabilities[s];
    }
    value += theta[ordering[rank]] - (shift + Math.log(total));

    for (let s = rank; s < n; s++) {
      probabilities[s] /= total;
    }
    gradient[ordering[rank]] += weight;
    for (let a = rank; a < n; a++) {
      gradient[ordering[a]] -= weight * probabilities[a];
      for (let b = rank; b < n; b++) {
        // diag(p) - p pᵀ, summed over choice sets. Duplicated identities land on the same entry,
        // which is exactly right: two seats of one identity are two draws from one strength (H2).
        information[ordering[a]][ordering[b]] +=
          weight * ((a === b ? probabilities[a] : 0) - probabilities[a] * probabilities[b]);
      }
    }
  }
  return value;
}

/**
 * Every strict ordering consistent with a pattern's tie groups, in a stable order.
 *
 * At most `4! = 24` for a four-way tie, and 1 for the untied case that is essentially every real
 * game. The enumeration is deliberately not short-circuited for the untied case beyond the trivial
 * single permutation, so the tied path is exercised by the same code the untied path uses.
 */
export function expandTies(pattern: RankingPattern): ReadonlyArray<ReadonlyArray<number>> {
  const cached = expansions.get(pattern);
  if (cached !== undefined) {
    return cached;
  }
  const expanded = expandTiesUncached(pattern);
  expansions.set(pattern, expanded);
  return expanded;
}

/**
 * Memoized per pattern **object**, which is what makes the memo safe: `buildPlacementSet` creates
 * each {@link RankingPattern} once and every cluster resample re-uses the same object, so the cache
 * is keyed on something immutable and cannot outlive it (a `WeakMap`). Keying on the pattern's
 * *contents* would be a global cache that a later, differently-indexed corpus could read stale
 * entries from.
 */
const expansions = new WeakMap<RankingPattern, ReadonlyArray<ReadonlyArray<number>>>();

function expandTiesUncached(pattern: RankingPattern): ReadonlyArray<ReadonlyArray<number>> {
  let orderings: Array<Array<number>> = [[]];
  for (const group of pattern.groups) {
    const expanded: Array<Array<number>> = [];
    for (const prefix of orderings) {
      for (const permutation of permutations(group)) {
        expanded.push([...prefix, ...permutation]);
      }
    }
    orderings = expanded;
  }
  return orderings;
}

function permutations(items: ReadonlyArray<number>): ReadonlyArray<ReadonlyArray<number>> {
  if (items.length <= 1) {
    return [items];
  }
  const result: Array<ReadonlyArray<number>> = [];
  for (let i = 0; i < items.length; i++) {
    const rest = [...items.slice(0, i), ...items.slice(i + 1)];
    for (const tail of permutations(rest)) {
      result.push([items[i], ...tail]);
    }
  }
  return result;
}

// ---------------------------------------------------------------------------------------------
// The fit
// ---------------------------------------------------------------------------------------------

export function fitPlackettLuce(set: PlacementSet, priorSigma = DEFAULT_PRIOR_SIGMA) {
  return fitStrengths(set.identities, (theta) => plackettLuceCurvature(theta, set.clusters), priorSigma);
}

/**
 * Fits a 3p or 4p pool: the MAP strengths, the two graphs, and the cluster-bootstrap replicates.
 *
 * The beat graph is built from **strict** finishes - `i` finished ahead of `j` in some game - with a
 * tie contributing an edge each way, which is the same reading `bradleyTerry.ts` gives a shared win.
 * That is what makes {@link boundedness}'s reachability argument say the same thing at 3p as at 2p:
 * an identity nothing has ever finished ahead of is separated, and its rating has no upper bound
 * from the data however large the fitted number looks.
 */
export function ratePlacements(
  rows: ReadonlyArray<Observation>,
  options: PoolFitOptions = {},
): PoolFit {
  const set = buildPlacementSet(rows);
  const priorSigma = options.priorSigma ?? DEFAULT_PRIOR_SIGMA;
  const fit = fitPlackettLuce(set, priorSigma);

  const beats = Array.from({length: set.identities.length}, () => new Set<number>());
  const played = Array.from({length: set.identities.length}, () => new Set<number>());
  for (const cluster of set.clusters) {
    for (const tally of cluster) {
      const flat = tally.pattern.groups.flat();
      for (const a of flat) {
        for (const b of flat) {
          if (a !== b) {
            played[a].add(b);
          }
        }
      }
      tally.pattern.groups.forEach((group, rank) => {
        for (const winner of group) {
          // Everyone strictly below, plus everyone tied with it - a tie is a shared result and reads
          // both ways, exactly as a shared win does at 2p (§3.2).
          for (const other of group) {
            if (other !== winner) {
              beats[winner].add(other);
            }
          }
          for (const lower of tally.pattern.groups.slice(rank + 1).flat()) {
            if (lower !== winner) {
              beats[winner].add(lower);
            }
          }
        }
      });
    }
  }

  return {
    ...fit,
    players: set.players,
    model: 'plackett-luce',
    games: set.games,
    groups: set.clusters.length,
    selfMatchGames: set.selfMatchGames,
    gamesPerIdentity: set.gamesPerIdentity,
    beats: beats.map((entry) => [...entry].sort((a, b) => a - b)),
    played: played.map((entry) => [...entry].sort((a, b) => a - b)),
    bootstrap: options.random === undefined ?
      undefined :
      bootstrapStrengths(
        set.clusters,
        (resample) => fitPlackettLuce({...set, clusters: resample}, priorSigma).strengths,
        {replicates: options.replicates ?? DEFAULT_BOOTSTRAP_REPLICATES, random: options.random},
        set.identities.length),
  };
}
